#!/usr/bin/env python3
"""Build the schema catalog manifest from curated family/doc-type lists."""

from __future__ import annotations

import json
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = REPO_ROOT / "Schemas" / "schema_catalog.json"


FAMILY_DOC_TYPES: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (
    (
        "fs",
        "consumer_lending",
        "Consumer Lending",
        (
            "Personal loan application",
            "Auto loan application",
            "Credit card application",
            "HELOC application",
            "Student loan application",
            "Buy-now-pay-later application",
            "Adverse action notice",
            "Credit approval / decline memo",
            "Loan estimate / closing disclosure",
            "Truth in Lending disclosure",
            "Promissory note",
            "Security agreement",
            "Guaranty agreement",
            "Payment deferral / modification agreement",
        ),
    ),
    (
        "fs",
        "commercial_lending",
        "Commercial Lending",
        (
            "Commercial loan application",
            "Borrowing base certificate",
            "Commercial credit memo",
            "Loan agreement",
            "Revolving credit agreement",
            "Term loan agreement",
            "Syndicated credit agreement",
            "Intercreditor agreement",
            "Subordination agreement",
            "Guaranty",
            "Security agreement",
            "UCC financing statement",
            "Collateral schedule",
            "Covenant compliance certificate",
            "Field examination report",
            "Appraisal / valuation report",
            "Environmental due diligence report",
            "Flood determination",
            "Insurance certificate",
            "Legal opinion letter",
            "Officer's certificate",
            "Board consent / corporate authorization",
        ),
    ),
    (
        "fs",
        "mortgage_real_estate_finance",
        "Mortgage and Real Estate Finance",
        (
            "Mortgage note",
            "Deed of trust / mortgage instrument",
            "Title commitment",
            "Title policy",
            "Appraisal report",
            "Property inspection report",
            "Purchase contract",
            "Homeowners insurance declaration",
            "Flood certificate",
            "Closing package",
            "Escrow analysis",
            "Servicing transfer notice",
            "Loss mitigation application",
            "Forbearance agreement",
            "Loan modification agreement",
            "Short sale package",
            "Foreclosure complaint / notice of default",
        ),
    ),
    (
        "fs",
        "deposit_treasury",
        "Deposit and Treasury",
        (
            "Deposit account application",
            "Signature card",
            "Account agreement",
            "Business account resolution",
            "ACH authorization",
            "Wire transfer agreement",
            "Treasury management agreement",
            "Remote deposit capture agreement",
            "Positive pay agreement",
            "Lockbox agreement",
            "Sweep account agreement",
            "Controlled disbursement agreement",
            "Account analysis statement",
            "Account closure request",
        ),
    ),
    (
        "fs",
        "payments_fintech",
        "Payments and Fintech",
        (
            "Merchant onboarding application",
            "Merchant processing agreement",
            "Payment facilitator agreement",
            "Sub-merchant application",
            "Card program agreement",
            "BIN sponsorship agreement",
            "NACHA compliance package",
            "Chargeback case file",
            "Dispute evidence package",
            "Payment exception report",
            "Fraud investigation file",
            "Reserve / holdback agreement",
            "Settlement statement",
        ),
    ),
    (
        "fs",
        "wealth_brokerage_investment",
        "Wealth, Brokerage, and Investment",
        (
            "Brokerage account application",
            "Investment advisory agreement",
            "Suitability questionnaire",
            "Investor profile",
            "Risk tolerance questionnaire",
            "Options trading agreement",
            "Margin agreement",
            "IRA adoption agreement",
            "Trust account opening package",
            "Beneficiary designation",
            "Transfer-on-death form",
            "Accredited investor certification",
            "Subscription agreement",
            "Private placement memorandum",
            "Capital call notice",
            "Distribution notice",
        ),
    ),
    (
        "fs",
        "kyc_aml_sanctions",
        "KYC, AML, and Sanctions",
        (
            "CIP record",
            "Customer risk assessment",
            "Enhanced due diligence memo",
            "Beneficial ownership certification",
            "Source of funds declaration",
            "Source of wealth declaration",
            "Sanctions screening result",
            "PEP review memo",
            "Adverse media review",
            "AML alert",
            "AML investigation case file",
            "Suspicious Activity Report support file",
            "Currency Transaction Report support file",
            "OFAC blocking / rejection report",
            "314(a) / 314(b) information-sharing record",
            "Periodic KYC refresh package",
            "Customer offboarding memo",
        ),
    ),
    (
        "healthcare",
        "healthcare_claims",
        "Healthcare Claims",
        (
            "EOB / CMS-1500",
            "UB-04 claim",
            "Dental claim form",
            "Vision claim form",
            "Remittance advice 835",
            "Claim denial letter",
            "Claim appeal letter",
            "Coordination of benefits form",
            "Explanation of payment",
            "Superbill",
            "Itemized medical bill",
            "Ambulance claim",
            "Workers compensation medical bill",
            "Out-of-network claim",
            "Secondary payer claim",
        ),
    ),
    (
        "healthcare",
        "clinical_documents",
        "Clinical Documents",
        (
            "Clinical Note SOAP",
            "History and physical",
            "Discharge summary",
            "Operative report",
            "Emergency department note",
            "Progress note",
            "Consultation note",
            "Nursing note",
            "Care plan",
            "Medication administration record",
            "Problem list",
            "Allergy list",
            "Immunization record",
            "Medical record request",
            "Continuity of care document",
            "Patient summary",
        ),
    ),
    (
        "healthcare",
        "healthcare_authorization",
        "Healthcare Authorization",
        (
            "Prior Authorization",
            "Medication prior authorization",
            "Referral authorization",
            "Precertification request",
            "Utilization review determination",
            "Medical necessity letter",
            "Authorization denial letter",
            "Peer-to-peer review packet",
            "Concurrent review packet",
            "Retro authorization request",
            "Appeal grievance case",
            "Coverage determination request",
        ),
    ),
    (
        "healthcare",
        "revenue_cycle",
        "Revenue Cycle",
        (
            "Patient registration form",
            "Insurance eligibility verification",
            "Patient financial responsibility form",
            "Good faith estimate",
            "No Surprises Act notice",
            "Patient payment plan",
            "Charity care application",
            "Financial assistance determination",
            "Medical lien notice",
            "Provider invoice",
            "Charge capture sheet",
            "Coding audit worksheet",
            "Accounts receivable aging report",
            "Denial management worklist",
        ),
    ),
    (
        "healthcare",
        "pharmacy",
        "Pharmacy",
        (
            "Prescription",
            "Pharmacy claim",
            "Medication therapy management note",
            "Formulary exception request",
            "Step therapy exception request",
            "Drug utilization review",
            "Specialty pharmacy enrollment",
            "Prior authorization pharmacy packet",
            "Medication reconciliation",
            "Controlled substance prescription",
            "Pharmacy benefit appeal",
        ),
    ),
    (
        "healthcare",
        "imaging_diagnostics",
        "Imaging and Diagnostics",
        (
            "Lab Report",
            "Radiology report",
            "Pathology report",
            "Genetic test report",
            "Molecular diagnostics report",
            "Imaging order",
            "Diagnostic test order",
            "Ultrasound report",
            "CT report",
            "MRI report",
            "X-ray report",
            "Cardiology diagnostic report",
            "EKG report",
            "Sleep study report",
        ),
    ),
    (
        "healthcare",
        "care_management",
        "Care Management",
        (
            "Case management assessment",
            "Care management plan",
            "Disease management assessment",
            "Transition of care note",
            "Home health certification",
            "Skilled nursing facility assessment",
            "Long-term care assessment",
            "Behavioral health assessment",
            "Social determinants screening",
            "Risk stratification report",
            "Remote patient monitoring report",
            "Discharge planning note",
        ),
    ),
    (
        "healthcare",
        "patient_access",
        "Patient Access",
        (
            "Patient intake form",
            "Consent to treat",
            "HIPAA acknowledgment",
            "Release of information authorization",
            "Advance directive",
            "Power of attorney healthcare",
            "Minor consent form",
            "Telehealth consent",
            "Patient demographics form",
            "Emergency contact form",
            "New patient questionnaire",
        ),
    ),
    (
        "healthcare",
        "quality_reporting",
        "Quality Reporting",
        (
            "HEDIS quality measure packet",
            "CMS star ratings evidence",
            "HCC risk adjustment chart",
            "Risk adjustment attestation",
            "Quality gap closure evidence",
            "Clinical quality measure report",
            "Hospital readmission review",
            "Patient safety event report",
            "Infection control report",
            "Value-based care performance report",
            "Population health registry extract",
        ),
    ),
    (
        "healthcare",
        "provider_network",
        "Provider Network",
        (
            "Provider contract",
            "Credentialing application",
            "Recredentialing packet",
            "Provider roster",
            "Provider directory attestation",
            "Delegated credentialing audit",
            "Facility credentialing packet",
            "Network adequacy report",
            "Single case agreement",
            "Provider termination notice",
            "Provider rate sheet",
        ),
    ),
    (
        "healthcare",
        "healthcare_compliance",
        "Healthcare Compliance",
        (
            "HIPAA risk assessment",
            "Breach notification report",
            "CMS audit response",
            "OIG exclusion screening result",
            "Fraud waste abuse investigation",
            "Medical policy document",
            "Clinical guideline document",
            "Accreditation survey response",
            "Corrective action plan healthcare",
            "Compliance training attestation",
        ),
    ),
    (
        "fs",
        "regulatory_exams_audit",
        "Regulatory Exams and Audit",
        (
            "Regulatory exam request list",
            "Management response",
            "Matter requiring attention / MRA tracker",
            "Internal audit report",
            "Compliance testing report",
            "Model validation report",
            "Risk control self-assessment",
            "Issue management record",
            "Corrective action plan",
            "Policy exception request",
            "Third-party risk assessment",
            "Vendor due diligence package",
            "SOC 1 / SOC 2 report",
            "Business continuity plan",
            "Disaster recovery test report",
        ),
    ),
    (
        "fs",
        "privacy_data_governance",
        "Privacy and Data Governance",
        (
            "Privacy notice",
            "GLBA disclosure",
            "Data processing agreement",
            "Data sharing consent",
            "Consumer data deletion request",
            "Data subject access request",
            "Information security risk assessment",
            "Data retention policy",
            "Data breach incident report",
            "Incident response report",
            "Cybersecurity insurance claim package",
        ),
    ),
    (
        "legal",
        "corporate_governance",
        "Corporate Governance",
        (
            "Articles of incorporation",
            "Certificate of formation",
            "Operating agreement",
            "Bylaws",
            "Partnership agreement",
            "Board resolutions",
            "Shareholder consent",
            "Secretary certificate",
            "Incumbency certificate",
            "Good standing certificate",
            "Corporate ownership chart",
            "Cap table",
            "Stock purchase agreement",
            "Stockholders agreement",
            "Voting agreement",
            "Investor rights agreement",
        ),
    ),
    (
        "legal",
        "contracts",
        "Contracts",
        (
            "Master services agreement",
            "Statement of work",
            "Service-level agreement",
            "Vendor agreement",
            "Software license agreement",
            "SaaS agreement",
            "Data license agreement",
            "Referral agreement",
            "Distribution agreement",
            "Reseller agreement",
            "Non-disclosure agreement",
            "Employment agreement",
            "Consulting agreement",
            "Non-compete / non-solicit agreement",
            "Settlement agreement",
            "Release agreement",
        ),
    ),
    (
        "legal",
        "litigation_disputes",
        "Litigation and Disputes",
        (
            "Complaint",
            "Answer",
            "Motion",
            "Brief",
            "Discovery request",
            "Discovery response",
            "Subpoena",
            "Deposition transcript",
            "Expert report",
            "Litigation case file",
            "Settlement demand",
            "Mediation statement",
            "Arbitration claim",
            "Judgment",
            "Garnishment order",
            "Writ of execution",
            "Legal hold notice",
        ),
    ),
    (
        "legal",
        "bankruptcy_restructuring",
        "Bankruptcy and Restructuring",
        (
            "Chapter 7 filing",
            "Chapter 13 filing",
            "Proof of claim",
            "Claim objection",
            "Preference demand letter",
            "Forbearance agreement",
            "Restructuring support agreement",
            "Plan support agreement",
            "Assignment for benefit of creditors",
            "Receivership order",
            "UCC Article 9 foreclosure notice",
            "Deed in lieu agreement",
            "Intercreditor standstill notice",
        ),
    ),
    (
        "insurance",
        "insurance_collateral_protection",
        "Insurance and Collateral Protection",
        (
            "Insurance application",
            "Policy declaration page",
            "Certificate of insurance",
            "Lender's loss payable endorsement",
            "Force-placed insurance notice",
            "Insurance claim file",
            "Proof of loss",
            "Subrogation notice",
            "Bond / surety agreement",
            "Title insurance claim",
            "Mortgage insurance certificate",
            "Private mortgage insurance cancellation notice",
        ),
    ),
    (
        "fs",
        "tax_financial_reporting",
        "Tax and Financial Reporting",
        (
            "Tax return package",
            "W-9",
            "W-8BEN / W-8BEN-E",
            "1099",
            "K-1",
            "Financial statements",
            "Audited financial report",
            "Reviewed financial statement",
            "Compiled financial statement",
            "Management accounts",
            "Trial balance",
            "General ledger extract",
            "Bank statement",
            "Cash flow statement",
            "Accounts receivable aging",
            "Accounts payable aging",
            "Budget / forecast",
            "Solvency certificate",
        ),
    ),
    (
        "fs",
        "regulatory_reporting",
        "Regulatory Reporting",
        (
            "Regulatory reporting package",
        ),
    ),
    (
        "insurance",
        "insurance_underwriting",
        "Insurance Underwriting",
        (
            "Insurance policy application",
            "Life insurance application",
            "Commercial insurance application",
            "Property insurance application",
            "Casualty insurance application",
            "Health insurance application",
            "Underwriting questionnaire",
            "Risk inspection report",
            "Loss run report",
            "Actuarial rating worksheet",
            "Policy quote",
            "Binder",
        ),
    ),
    (
        "insurance",
        "insurance_policy_admin",
        "Insurance Policy Administration",
        (
            "Policy declaration page",
            "Insurance policy",
            "Policy endorsement",
            "Policy renewal notice",
            "Policy cancellation notice",
            "Certificate of insurance",
            "Evidence of insurance",
            "Named insured change request",
            "Beneficiary change form",
            "Premium audit report",
            "Reinstatement request",
        ),
    ),
    (
        "insurance",
        "insurance_claims",
        "Insurance Claims",
        (
            "Insurance claim file",
            "First notice of loss",
            "Proof of loss",
            "Claims adjuster report",
            "Subrogation notice",
            "Claim denial letter",
            "Claim settlement agreement",
            "Medical claims packet",
            "Property damage estimate",
            "Auto damage appraisal",
            "Workers compensation claim",
            "Title insurance claim",
        ),
    ),
    (
        "manufacturing",
        "procurement_supply_chain",
        "Procurement and Supply Chain",
        (
            "Purchase order",
            "Supplier quote",
            "Supplier contract",
            "Bill of materials",
            "Material requisition",
            "Advance shipping notice",
            "Packing slip",
            "Receiving report",
            "Supplier scorecard",
            "Inventory count sheet",
            "Demand forecast",
            "Production schedule",
        ),
    ),
    (
        "manufacturing",
        "manufacturing_quality",
        "Manufacturing Quality",
        (
            "Quality inspection report",
            "Certificate of analysis",
            "Certificate of conformity",
            "Nonconformance report",
            "Corrective preventive action",
            "Production batch record",
            "Device history record",
            "Process control plan",
            "First article inspection",
            "Supplier corrective action request",
            "Calibration certificate",
            "ISO audit report",
        ),
    ),
    (
        "manufacturing",
        "manufacturing_operations",
        "Manufacturing Operations",
        (
            "Work order",
            "Manufacturing traveler",
            "Maintenance work order",
            "Equipment downtime report",
            "Safety incident report",
            "Environmental health safety audit",
            "Change control request",
            "Engineering change order",
            "Deviation report",
            "Production yield report",
        ),
    ),
    (
        "real_estate",
        "real_estate_transactions",
        "Real Estate Transactions",
        (
            "Purchase agreement",
            "Lease agreement",
            "Title commitment",
            "Title policy",
            "Property appraisal",
            "Property inspection report",
            "Closing statement",
            "Escrow instruction",
            "Deed",
            "Easement agreement",
            "Zoning report",
            "Environmental site assessment",
        ),
    ),
    (
        "real_estate",
        "property_management",
        "Property Management",
        (
            "Property management agreement",
            "Rent roll",
            "Lease abstract",
            "Tenant estoppel certificate",
            "Service contract",
            "CAM reconciliation",
            "Maintenance request",
            "Move-in inspection",
            "Move-out inspection",
            "Security deposit statement",
            "Eviction notice",
        ),
    ),
    (
        "real_estate",
        "commercial_real_estate_finance",
        "Commercial Real Estate Finance",
        (
            "Commercial real estate loan application",
            "Rent roll certificate",
            "Operating statement",
            "Debt service coverage analysis",
            "Property condition assessment",
            "Phase I environmental report",
            "Tenant lease schedule",
            "Borrower organizational chart",
            "Guarantor financial statement",
        ),
    ),
)


AVAILABLE_OVERRIDES: dict[str, str] = {
    "aml_sar": "AML Suspicious Activity Report",
    "clinical_note_soap": "Clinical Note SOAP",
    "court_filing": "Court Filing",
    "eob_cms1500": "EOB / CMS-1500",
    "invoice": "Invoice",
    "kyc_cdd_form": "KYC / CDD Form",
    "lab_report": "Lab Report",
    "mortgage_application": "Mortgage Application",
    "nda_msa": "NDA / MSA",
    "prior_auth": "Prior Authorization",
    "regulatory_submission": "Regulatory Submission",
    "sow": "Statement of Work",
}

AVAILABLE_DOC_TYPES = {
    "commercial_loan_application",
    "commercial_credit_memo",
    "loan_agreement",
    "covenant_compliance_certificate",
    "collateral_schedule",
    "ucc_financing_statement",
    "guaranty_agreement",
    "issue_management_record",
    "litigation_case_file",
    "merchant_onboarding_application",
    "regulatory_reporting_package",
    "security_agreement",
    "syndicated_credit_agreement",
    "third_party_risk_assessment",
    "trust_account_opening_package",
    *AVAILABLE_OVERRIDES.keys(),
}

REGULATORY_ALIGNMENT_BY_FAMILY = {
    "bankruptcy_restructuring": "U.S. Bankruptcy Code, Bankruptcy Rules, docket and claims administration",
    "collateral_perfection": "UCC Article 9 perfection, lien monitoring, secured lending controls",
    "commercial_lending": "Commercial credit policy, UCC Article 9, safety and soundness guidance",
    "consumer_lending": "ECOA, Reg B, TILA, FCRA, UDAAP, consumer lending controls",
    "contracts": "Contract lifecycle management, obligations, renewal, and legal operations controls",
    "corporate_governance": "Corporate authority, entity governance, board and ownership records",
    "deposit_treasury": "Deposit operations, treasury management, NACHA, wire and account controls",
    "care_management": "Care coordination, transitions of care, utilization management, and population health workflows",
    "clinical_documents": "HL7 FHIR, clinical documentation, care delivery, and EHR interoperability workflows",
    "healthcare_authorization": "HIPAA 278, utilization management, medical necessity, coverage determination, and appeals workflows",
    "healthcare_claims": "CMS-1500, UB-04, X12 837/835, HIPAA 5010, payer adjudication, and claims operations",
    "healthcare_compliance": "HIPAA, CMS, OIG, accreditation, healthcare compliance, and audit response workflows",
    "imaging_diagnostics": "LOINC, HL7 FHIR DiagnosticReport, radiology, pathology, laboratory, and diagnostic order workflows",
    "insurance_claims": "NAIC model laws, claims handling, proof of loss, settlement, subrogation, and coverage determination workflows",
    "insurance_collateral_protection": "Collateral protection, insurance evidence, claims, and lender loss payee controls",
    "insurance_policy_admin": "Policy servicing, declarations, endorsements, renewal, cancellation, certificates, and evidence of insurance",
    "insurance_underwriting": "Insurance application intake, underwriting, risk inspection, pricing, rating, and binder workflows",
    "kyc_aml_sanctions": "BSA/AML, FinCEN CDD/CIP, OFAC, FFIEC BSA/AML guidance",
    "litigation_disputes": "Matter management, court filings, discovery, judgments, and legal hold workflows",
    "mortgage_real_estate_finance": "TRID, RESPA, TILA, HMDA, servicing, foreclosure, and real estate finance controls",
    "payments_fintech": "NACHA, card network rules, merchant acquiring, dispute, fraud, and settlement controls",
    "commercial_real_estate_finance": "CRE underwriting, collateral, property financials, lease schedules, and environmental due diligence",
    "manufacturing_operations": "Work orders, production execution, maintenance, EHS, change control, and yield reporting",
    "manufacturing_quality": "ISO 9001, IATF 16949, quality records, nonconformance, CAPA, inspection, and batch traceability",
    "procurement_supply_chain": "Purchase orders, supplier records, receiving, inventory, demand planning, and supplier performance",
    "patient_access": "Patient registration, consent, privacy authorization, eligibility, and front-door access workflows",
    "pharmacy": "NCPDP, medication access, formulary, specialty pharmacy, controlled substance, and pharmacy benefit workflows",
    "privacy_data_governance": "GLBA, privacy rights, data governance, incident response, and security controls",
    "regulatory_exams_audit": "Regulatory exam management, internal audit, issue management, and corrective action governance",
    "regulatory_reporting": "Call Report, HMDA, CRA, SAR/CTR, CECL, CCAR/DFAST, liquidity, and institution-specific regulatory reporting workflows",
    "provider_network": "Provider credentialing, contracting, network adequacy, directory, and delegated oversight workflows",
    "quality_reporting": "HEDIS, CMS Star Ratings, risk adjustment, quality gap closure, and value-based care reporting",
    "property_management": "Lease administration, rent roll, CAM, maintenance, tenant notices, and property operations",
    "real_estate_transactions": "Purchase, lease, title, escrow, inspection, appraisal, zoning, and closing workflows",
    "tax_financial_reporting": "Tax reporting, financial statement analysis, covenant monitoring, and credit analytics",
    "wealth_brokerage_investment": "SEC/FINRA suitability, advisory, brokerage, retirement, and private investment workflows",
}


def slugify(display_name: str) -> str:
    value = display_name.lower()
    value = value.replace("314(a)", "314a").replace("314(b)", "314b")
    value = value.replace("w-8ben", "w_8ben").replace("w-9", "w_9")
    value = value.replace("k-1", "k_1")
    value = value.replace("1099", "form_1099")
    value = value.replace("ofac", "ofac")
    value = value.replace("ucc", "ucc")
    value = value.replace("ach", "ach")
    value = value.replace("bin", "bin")
    value = value.replace("nacha", "nacha")
    value = value.replace("&", " and ")
    value = re.sub(r"[/+-]", " ", value)
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    return value


def normalize_doc_type(family: str, display_name: str, used: set[str]) -> str:
    aliases = {
        ("clinical_documents", "Clinical Note SOAP"): "clinical_note_soap",
        ("healthcare_authorization", "Prior Authorization"): "prior_auth",
        ("healthcare_claims", "EOB / CMS-1500"): "eob_cms1500",
        ("imaging_diagnostics", "Lab Report"): "lab_report",
        ("consumer_lending", "Guaranty agreement"): "consumer_guaranty_agreement",
        ("consumer_lending", "Security agreement"): "consumer_security_agreement",
        ("commercial_lending", "Guaranty"): "guaranty_agreement",
        ("commercial_lending", "Security agreement"): "security_agreement",
        ("contracts", "Statement of work"): "sow",
    }
    slug = aliases.get((family, display_name), slugify(display_name))
    if slug not in used:
        return slug
    return f"{family}_{slug}"


def build_entry(
    *,
    vertical: str,
    family: str,
    family_display_name: str,
    display_name: str,
    doc_type: str,
) -> dict[str, object]:
    availability = "available" if doc_type in AVAILABLE_DOC_TYPES else "future"
    return {
        "vertical": vertical,
        "family": family,
        "family_display_name": family_display_name,
        "doc_type": doc_type,
        "display_name": display_name,
        "priority": 1 if availability == "available" else 2,
        "availability": availability,
        "rollout_status": "registry_ready" if availability == "available" else "backlog",
        "aliases": [],
        "regulatory_alignment": REGULATORY_ALIGNMENT_BY_FAMILY.get(family, ""),
    }


def main() -> int:
    used: set[str] = set()
    entries: list[dict[str, object]] = []

    for vertical, family, family_display_name, doc_names in FAMILY_DOC_TYPES:
        for display_name in doc_names:
            doc_type = normalize_doc_type(family, display_name, used)
            used.add(doc_type)
            entries.append(
                build_entry(
                    vertical=vertical,
                    family=family,
                    family_display_name=family_display_name,
                    display_name=display_name,
                    doc_type=doc_type,
                )
            )

    for doc_type, display_name in sorted(AVAILABLE_OVERRIDES.items()):
        if doc_type in used:
            continue
        used.add(doc_type)
        vertical = "healthcare" if doc_type in {"eob_cms1500", "clinical_note_soap", "lab_report", "prior_auth"} else "legal"
        if doc_type in {"mortgage_application", "kyc_cdd_form", "aml_sar", "invoice"}:
            vertical = "fs"
        family = {
            "aml_sar": "kyc_aml_sanctions",
            "clinical_note_soap": "clinical_documents",
            "court_filing": "litigation_disputes",
            "eob_cms1500": "healthcare_claims",
            "invoice": "accounts_payable",
            "kyc_cdd_form": "kyc_aml_sanctions",
            "lab_report": "clinical_documents",
            "mortgage_application": "mortgage_real_estate_finance",
            "nda_msa": "contracts",
            "prior_auth": "healthcare_authorization",
            "regulatory_submission": "regulatory_exams_audit",
            "sow": "contracts",
        }[doc_type]
        entries.append(
            build_entry(
                vertical=vertical,
                family=family,
                family_display_name=family.replace("_", " ").title(),
                display_name=display_name,
                doc_type=doc_type,
            )
        )

    entries.sort(key=lambda item: (str(item["vertical"]), str(item["family"]), str(item["display_name"])))
    catalog = {
        "schema_catalog_version": "2026-06-05",
        "rollout_notes": "Superset catalog of high-value banking, compliance, legal, insurance, and financial reporting document families. availability=available means a registry-ready schema bundle or existing bundled extractor coverage exists; availability=future means backlog candidate.",
        "availability_values": ["available", "future"],
        "document_types": entries,
    }
    CATALOG_PATH.write_text(json.dumps(catalog, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(entries)} schema catalog entries to {CATALOG_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
